# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7ccd641f5c83772137e12d0106eaa4b5ca092c8c12e64efbf7e59601a66020a5d3bd01ca8aae45ff3516d31c5dc7c924e9a001ede2285347e94ab2dba76d63

test:
  secret_key_base: f4809ea917af15ea1c65c3de18d7a1d0bc95eb3536b8f80a33c53d4a0d5842bb9216ec8926b794e142ad02c65a844c2241cc50d7ddc2a064bdddfd9d05140a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
