Production.create!(name: "Flux Capacitor", price: 19.55, category: "Electronics")
Production.create!(name: "Red Shirt", price: 12.49, category: "Clothing")
Production.create!(name: "Oak Coffee Table", price: 223.99, category: "Furniture")
Production.create!(name: "Video Game", price: 29.95, category: "Electronics")
Production.create!(name: "Game Console", price: 299.95, category: "Electronics")
Production.create!(name: "Technodrome", price: 27.99, category: "Toys & Games")
Production.create!(name: "Oh's Cereal", price: 3.95, category: "Foods")
Production.create!(name: "Lawn Chair", price: 34.99, category: "Furniture")
Production.create!(name: "Dog Toy Bone", price: 2.99, category: "Toys & Games")
Production.create!(name: "Cat Toy", price: 2.99, category: "Toys & Games")
Production.create!(name: "Heated Blanket", price: 27.95, category: "Furniture")
Production.create!(name: "Chocolate Pie", price: 3.14, category: "Foods")
Production.create!(name: "Acoustic Guitar", price: 1025.00, category: "Toys & Games")
Production.create!(name: "Model Enterprise", price: 27.99, category: "Toys & Games")
Production.create!(name: "Agricola", price: 45.99, category: "Toys & Games")
Production.create!(name: "Stone Age", price: 34.99, category: "Toys & Games")
Production.create!(name: "7 Wonders", price: 28.75, category: "Toys & Games")
Production.create!(name: "Settlers of Catan", price: 34.95, category: "Toys & Games")
Production.create!(name: "Seafarers of Catan", price: 19.95, category: "Toys & Games")
Production.create!(name: "Knights of Catan", price: 19.95, category: "Toys & Games")
Production.create!(name: "Starfarers of Catan", price: 19.95, category: "Toys & Games")
Production.create!(name: "Millennium Falcon", price: 3597200.00, category: "Toys & Games")
Production.create!(name: "Answer to Everything", price: 42.00, category: "Misc")
Production.create!(name: "Box Kite", price: 63.00, category: "Toys & Games")
Production.create!(name: "1000 Piece Jigsaw Puzzle", price: 14.99, category: "Toys & Games")
Production.create!(name: "Rubber Ducky", price: 4.75, category: "Toys & Games")
Production.create!(name: "Unicorn Action Figure", price: 8.75, category: "Toys & Games")
Production.create!(name: "Rack", price: 32.49, category: "Furniture")
Production.create!(name: "Model Train Rails", price: 45.00, category: "Toys & Games")
Production.create!(name: "CanCan Music Record", price: 2.99, category: "Electronics")
